// <auto-generated />
using System;
using LocalAgentPlatform.Shared.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LocalAgentPlatform.Shared.Data.Migrations
{
    [DbContext(typeof(PlatformDbContext))]
    [Migration("20261008063621_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LocalAgentPlatform.Shared.Data.Entities.AgentSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FailureReason")
                        .HasColumnType("text");

                    b.Property<string>("FinalSummary")
                        .HasColumnType("text");

                    b.Property<int>("IterationCount")
                        .HasColumnType("integer");

                    b.Property<int>("MaxDurationMinutes")
                        .HasColumnType("integer");

                    b.Property<int>("MaxIterations")
                        .HasColumnType("integer");

                    b.Property<int>("MaxRepairAttempts")
                        .HasColumnType("integer");

                    b.Property<int>("MaxRetries")
                        .HasColumnType("integer");

                    b.Property<string>("ModelIdUsed")
                        .HasColumnType("text");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("PlanJson")
                        .HasColumnType("text");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<int>("RepairAttemptCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("RepositoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserRequest")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("State");

                    b.HasIndex("OwnerUserId", "CreatedAtUtc");

                    b.ToTable("AgentSessions");
                });

            modelBuilder.Entity("LocalAgentPlatform.Shared.Data.Entities.AgentTaskNode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AgentSessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("ArgumentsJson")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DependenciesJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Error")
                        .HasColumnType("text");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<string>("Output")
                        .HasColumnType("text");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StepKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ToolName")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AgentSessionId", "OrderIndex");

                    b.HasIndex("AgentSessionId", "StepKey")
                        .IsUnique();

                    b.ToTable("AgentTaskNodes");
                });

            modelBuilder.Entity("LocalAgentPlatform.Shared.Data.Entities.ApiKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("KeyHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("KeyPrefix")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("LastUsedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("KeyHash")
                        .IsUnique();

                    b.ToTable("ApiKeys");
                });

            modelBuilder.Entity("LocalAgentPlatform.Shared.Data.Entities.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("MfaEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("MfaSecretProtected")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RecoveryCodeHash")
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Role");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("LocalAgentPlatform.Shared.Data.Entities.AuditLogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Detail")
                        .HasColumnType("text");

                    b.Property<string>("ModelId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ToolName")
                        .HasColumnType("text");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAtUtc");

                    b.ToTable("AuditLogEntries");
                });

            modelBuilder.Entity("LocalAgentPlatform.Shared.Data.Entities.CodeRelationship", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("FromSymbolId")
                        .HasColumnType("uuid");

                    b.Property<string>("RelationshipType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RepositoryId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ToSymbolId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FromSymbolId");

                    b.HasIndex("ToSymbolId");

                    b.ToTable("CodeRelationships");
                });

            modelBuilder.Entity("LocalAgentPlatform.Shared.Data.Entities.CodeSymbol", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContainingNamespace")
                        .HasColumnType("text");

                    b.Property<string>("ContainingTypeName")
                        .HasColumnType("text");

                    b.Property<Guid>("FileSnapshotId")
                        .HasColumnType("uuid");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("LineNumber")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RepositoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Signature")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FileSnapshotId");

                    b.HasIndex("RepositoryId", "Name");

                    b.ToTable("CodeSymbols");
                });

            modelBuilder.Entity("LocalAgentPlatform.Shared.Data.Entities.CommandPermissionRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExecutableName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUserId", "ExecutableName")
                        .IsUnique();

                    b.ToTable("CommandPermissionRules");
                });

            modelBuilder.Entity("LocalAgentPlatform.Shared.Data.Entities.FileSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Language")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("LastIndexedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RepositoryId")
                        .HasColumnType("uuid");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ContentHash");

                    b.HasIndex("RepositoryId", "RelativePath")
                        .IsUnique();

                    b.ToTable("FileSnapshots");
                });

            modelBuilder.Entity("LocalAgentPlatform.Shared.Data.Entities.MemoryEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessCount")
                        .HasColumnType("integer");

                    b.Property<double>("BaseImportance")
                        .HasColumnType("double precision");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EmbeddingJson")
                        .HasColumnType("text");

                    b.Property<string>("EmbeddingModelId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("LastAccessedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RepositoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("SourceAgentSessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Tags")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("OwnerUserId", "RepositoryId", "Scope");

                    b.ToTable("MemoryEntries");
                });

            modelBuilder.Entity("LocalAgentPlatform.Shared.Data.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUserId", "Name")
                        .IsUnique();

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("LocalAgentPlatform.Shared.Data.Entities.RegisteredModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("ContextWindow")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<string>("ModelId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProviderId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Quantization")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("RegisteredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProviderId", "ModelId")
                        .IsUnique();

                    b.ToTable("RegisteredModels");
                });

            modelBuilder.Entity("LocalAgentPlatform.Shared.Data.Entities.Repository", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DefaultBranch")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("LastIndexedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LocalPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LocalPath");

                    b.HasIndex("ProjectId");

                    b.ToTable("Repositories");
                });

            modelBuilder.Entity("LocalAgentPlatform.Shared.Data.Entities.RepositoryIndexingJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<int>("FilesChanged")
                        .HasColumnType("integer");

                    b.Property<int>("FilesDeleted")
                        .HasColumnType("integer");

                    b.Property<int>("FilesScanned")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("QueuedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RepositoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SymbolsExtracted")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RepositoryId", "QueuedAtUtc");

                    b.ToTable("RepositoryIndexingJobs");
                });

            modelBuilder.Entity("LocalAgentPlatform.Shared.Data.Entities.TokenUsageRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AgentSessionId")
                        .HasColumnType("uuid");

                    b.Property<int>("CachedTokens")
                        .HasColumnType("integer");

                    b.Property<int>("ContextWindowMax")
                        .HasColumnType("integer");

                    b.Property<int>("InputTokens")
                        .HasColumnType("integer");

                    b.Property<int>("OutputTokens")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("RecordedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeSpan?>("TimeToFirstToken")
                        .HasColumnType("interval");

                    b.Property<double>("TokensPerSecond")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("AgentSessionId");

                    b.ToTable("TokenUsageRecords");
                });

            modelBuilder.Entity("LocalAgentPlatform.Shared.Data.Entities.ToolDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DefaultTimeoutSeconds")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("RegisteredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("RequiresApproval")
                        .HasColumnType("boolean");

                    b.Property<string>("RiskLevel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ToolDefinitions");
                });

            modelBuilder.Entity("LocalAgentPlatform.Shared.Data.Entities.ToolExecution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ArgumentsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DecisionReason")
                        .HasColumnType("text");

                    b.Property<string>("Error")
                        .HasColumnType("text");

                    b.Property<int?>("ExitCode")
                        .HasColumnType("integer");

                    b.Property<string>("Output")
                        .HasColumnType("text");

                    b.Property<Guid?>("OwnerUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RepositoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("RequestedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool?>("Success")
                        .HasColumnType("boolean");

                    b.Property<string>("ToolName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WorkspaceRootPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RequestedAtUtc");

                    b.HasIndex("ToolName");

                    b.HasIndex("OwnerUserId", "RequestedAtUtc");

                    b.ToTable("ToolExecutions");
                });

            modelBuilder.Entity("LocalAgentPlatform.Shared.Data.Entities.VerificationRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AgentSessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("BuildOutputSummary")
                        .HasColumnType("text");

                    b.Property<bool?>("BuildPassed")
                        .HasColumnType("boolean");

                    b.Property<int?>("CompilerErrorCount")
                        .HasColumnType("integer");

                    b.Property<int?>("CompilerWarningCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OverallResult")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RepairAttemptNumber")
                        .HasColumnType("integer");

                    b.Property<string>("ReviewerReason")
                        .HasColumnType("text");

                    b.Property<string>("ReviewerVerdict")
                        .HasColumnType("text");

                    b.Property<int>("SecurityFindingCount")
                        .HasColumnType("integer");

                    b.Property<string>("SecurityFindingsJson")
                        .HasColumnType("text");

                    b.Property<string>("TestOutputSummary")
                        .HasColumnType("text");

                    b.Property<int?>("TestsFailed")
                        .HasColumnType("integer");

                    b.Property<bool?>("TestsPassed")
                        .HasColumnType("boolean");

                    b.Property<bool?>("TestsRan")
                        .HasColumnType("boolean");

                    b.Property<int?>("TestsSkipped")
                        .HasColumnType("integer");

                    b.Property<int?>("TestsTotal")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AgentSessionId", "RepairAttemptNumber");

                    b.ToTable("VerificationRuns");
                });

            modelBuilder.Entity("LocalAgentPlatform.Shared.Data.Entities.AgentTaskNode", b =>
                {
                    b.HasOne("LocalAgentPlatform.Shared.Data.Entities.AgentSession", "AgentSession")
                        .WithMany("Tasks")
                        .HasForeignKey("AgentSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AgentSession");
                });

            modelBuilder.Entity("LocalAgentPlatform.Shared.Data.Entities.CodeSymbol", b =>
                {
                    b.HasOne("LocalAgentPlatform.Shared.Data.Entities.FileSnapshot", "FileSnapshot")
                        .WithMany("Symbols")
                        .HasForeignKey("FileSnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FileSnapshot");
                });

            modelBuilder.Entity("LocalAgentPlatform.Shared.Data.Entities.FileSnapshot", b =>
                {
                    b.HasOne("LocalAgentPlatform.Shared.Data.Entities.Repository", "Repository")
                        .WithMany()
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Repository");
                });

            modelBuilder.Entity("LocalAgentPlatform.Shared.Data.Entities.Repository", b =>
                {
                    b.HasOne("LocalAgentPlatform.Shared.Data.Entities.Project", "Project")
                        .WithMany("Repositories")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("LocalAgentPlatform.Shared.Data.Entities.TokenUsageRecord", b =>
                {
                    b.HasOne("LocalAgentPlatform.Shared.Data.Entities.AgentSession", "AgentSession")
                        .WithMany("TokenUsages")
                        .HasForeignKey("AgentSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AgentSession");
                });

            modelBuilder.Entity("LocalAgentPlatform.Shared.Data.Entities.AgentSession", b =>
                {
                    b.Navigation("Tasks");

                    b.Navigation("TokenUsages");
                });

            modelBuilder.Entity("LocalAgentPlatform.Shared.Data.Entities.FileSnapshot", b =>
                {
                    b.Navigation("Symbols");
                });

            modelBuilder.Entity("LocalAgentPlatform.Shared.Data.Entities.Project", b =>
                {
                    b.Navigation("Repositories");
                });
#pragma warning restore 612, 618
        }
    }
}
